/** \file 
Fichier traitant de la communication série (UART).
\author    Adrien Jaegy
 */

#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#define TYPE_TRAME_CON_TEST_COM 129
#define TYPE_TRAME_CON_DEPART 130
#define TYPE_TRAME_CON_STOP 131
#define TYPE_TRAME_INF_ETAT 1
#define TYPE_TRAME_INF_ETAT_BATTERIE 4
#define TYPE_TRAME_INF_ANGLE_HORS_INTERVALLE 5
#define TYPE_TRAME_INF_ANGLE_TANGAGE 6
#define TYPE_TRAME_INF_VITESSE_ANGULAIRE 7
#define TYPE_TRAME_INF_VERBOSE 8
#define TYPE_TRAME_CON_VERBOSE 136
#define TYPE_TRAME_INF_VITESSED 12
#define TYPE_TRAME_INF_VITESSEG 13
#define TYPE_TRAME_INF_DISTANCE_PARCOURUE 14
#define TYPE_TRAME_INF_ACCELERATION 15
#define TYPE_TRAME_CON_CHARGER_VITESSE 144
#define TYPE_TRAME_CON_ENREGISTRER_VITESSE 145
#define TYPE_TRAME_CON_CHARGER_ASSERVISSEMENT 146
#define TYPE_TRAME_CON_ENREGISTRER_ASSERVISSEMENT 147
#define TYPE_TRAME_CON_CHARGER_DEMARRAGE 148
#define TYPE_TRAME_CON_ENREGISTRER_DEMARRAGE 149
#define TYPE_TRAME_CON_PRINC_PID_K 150
#define TYPE_TRAME_CON_PRINC_PID_D 151
#define TYPE_TRAME_CON_PRINC_DIR 152
#define TYPE_TRAME_CON_COEF_KALMAN 153
#define TYPE_TRAME_CON_ACCELERATION_COEF_FILTRE 154
#define TYPE_TRAME_CON_GUIDONMAX 155
#define TYPE_TRAME_CON_LIMITE_DISTANCE_UTILISATEUR 156
#define TYPE_TRAME_CON_DEMARRAGE_TOL_ANGLE 157
#define TYPE_TRAME_CON_DEMARRAGE_TOL_GUIDON 158
#define TYPE_TRAME_CON_DEMARRAGE_DELAI_EQUILIBRE 159
#define TYPE_TRAME_CON_VITESSE_TROITTOIR_MAX 160
#define TYPE_TRAME_CON_POURCENT_SECURITE_MOTEUR 161
#define TYPE_TRAME_CON_COEF_HYSTERISIS_SECURITE 162
#define TYPE_TRAME_INF_PRINC_PID_K 22
#define TYPE_TRAME_INF_PRINC_PID_D 23
#define TYPE_TRAME_INF_PRINC_DIR 24
#define TYPE_TRAME_INF_COEF_KALMAN 25
#define TYPE_TRAME_INF_ACCELERATION_COEF_FILTRE 26
#define TYPE_TRAME_INF_GUIDONMAX 27
#define TYPE_TRAME_INF_LIMITE_DISTANCE_UTILISATEUR 28
#define TYPE_TRAME_INF_DEMARRAGE_TOL_ANGLE 29
#define TYPE_TRAME_INF_DEMARRAGE_TOL_GUIDON 30
#define TYPE_TRAME_INF_DEMARRAGE_DELAI_EQUILIBRE 31
#define TYPE_TRAME_INF_VITESSE_TROITTOIR_MAX 32
#define TYPE_TRAME_INF_POURCENT_SECURITE_MOTEUR 33
#define TYPE_TRAME_INF_COEF_HYSTERISIS_SECURITE 34
#define TYPE_TRAME_CON_COEF_COURANT_1 163
#define TYPE_TRAME_INF_COEF_COURANT_1 35
#define TYPE_TRAME_CON_COEF_COURANT_2 164
#define TYPE_TRAME_INF_COEF_COURANT_2 36
#define TYPE_TRAME_CON_COUPLED 178
#define TYPE_TRAME_INF_COUPLED 50
#define TYPE_TRAME_CON_COUPLEG 179
#define TYPE_TRAME_INF_COUPLEG 51
#define TYPE_TRAME_INF_ERREUR_CARTE_COURANT 52
#define TYPE_TRAME_INF_PRET 53
#define TYPE_TRAME_CON_DEMANDE_COEFFICIENTS 137

#define LG_TRAME_CON_TEST_COM 4
#define LG_TRAME_CON_DEPART 0
#define LG_TRAME_CON_STOP 0
#define LG_TRAME_INF_ETAT 1
#define LG_TRAME_INF_ETAT_BATTERIE 4
#define LG_TRAME_INF_ANGLE_HORS_INTERVALLE 1
#define LG_TRAME_INF_ANGLE_TANGAGE 4
#define LG_TRAME_INF_VITESSE_ANGULAIRE 4
#define LG_TRAME_INF_VERBOSE 2
#define LG_TRAME_CON_VERBOSE 2
#define LG_TRAME_INF_VITESSED 4
#define LG_TRAME_INF_VITESSEG 4
#define LG_TRAME_INF_DISTANCE_PARCOURUE 4
#define LG_TRAME_INF_ACCELERATION 4
#define LG_TRAME_CON_CHARGER_VITESSE 0
#define LG_TRAME_CON_ENREGISTRER_VITESSE 0
#define LG_TRAME_CON_CHARGER_ASSERVISSEMENT 0
#define LG_TRAME_CON_ENREGISTRER_ASSERVISSEMENT 0
#define LG_TRAME_CON_CHARGER_DEMARRAGE 0
#define LG_TRAME_CON_ENREGISTRER_DEMARRAGE 0
#define LG_TRAME_CON_PRINC_PID_K 4
#define LG_TRAME_CON_PRINC_PID_D 4
#define LG_TRAME_CON_PRINC_DIR 4
#define LG_TRAME_CON_COEF_KALMAN 4
#define LG_TRAME_CON_ACCELERATION_COEF_FILTRE 4
#define LG_TRAME_CON_GUIDONMAX 4
#define LG_TRAME_CON_LIMITE_DISTANCE_UTILISATEUR 4
#define LG_TRAME_CON_DEMARRAGE_TOL_ANGLE 4
#define LG_TRAME_CON_DEMARRAGE_TOL_GUIDON 4
#define LG_TRAME_CON_DEMARRAGE_DELAI_EQUILIBRE 4
#define LG_TRAME_CON_VITESSE_TROITTOIR_MAX 4
#define LG_TRAME_CON_POURCENT_SECURITE_MOTEUR 4
#define LG_TRAME_CON_COEF_HYSTERISIS_SECURITE 4
#define LG_TRAME_INF_PRINC_PID_K 4
#define LG_TRAME_INF_PRINC_PID_D 4
#define LG_TRAME_INF_PRINC_DIR 4
#define LG_TRAME_INF_COEF_KALMAN 4
#define LG_TRAME_INF_ACCELERATION_COEF_FILTRE 4
#define LG_TRAME_INF_GUIDONMAX 4
#define LG_TRAME_INF_LIMITE_DISTANCE_UTILISATEUR 4
#define LG_TRAME_INF_DEMARRAGE_TOL_ANGLE 4
#define LG_TRAME_INF_DEMARRAGE_TOL_GUIDON 4
#define LG_TRAME_INF_DEMARRAGE_DELAI_EQUILIBRE 4
#define LG_TRAME_INF_VITESSE_TROITTOIR_MAX 4
#define LG_TRAME_INF_POURCENT_SECURITE_MOTEUR 4
#define LG_TRAME_INF_COEF_HYSTERISIS_SECURITE 4
#define LG_TRAME_CON_COEF_COURANT_1 4
#define LG_TRAME_INF_COEF_COURANT_1 4
#define LG_TRAME_CON_COEF_COURANT_2 4
#define LG_TRAME_INF_COEF_COURANT_2 4
#define LG_TRAME_CON_COUPLED 4
#define LG_TRAME_INF_COUPLED 4
#define LG_TRAME_CON_COUPLEG 4
#define LG_TRAME_INF_COUPLEG 4
#define LG_TRAME_INF_ERREUR_CARTE_COURANT 1
#define LG_TRAME_INF_PRET 1
#define LG_TRAME_CON_DEMANDE_COEFFICIENTS 0


#define DEBUT_TRAME 114
#define TRAME_ERR_NOERR 0
#define TRAME_ERR_TYPE 1
#define TRAME_ERR_CHECK 2
#define TRAME_ERR_DEBUT 3

/*!
Pour envoyer une donnée sous forme de trame sur le port 1.
\param[in] type   type de trame (voir liste des defines commancants par TYPE_TRAME_...
\param[in] data   le pointeur de la donnée à envoyer
\param[in] data_length  longueur de la trame (voir liste des defines commancants par LG_TRAME_...
*/
void envoiTrameUart1 (char type, void * data, char data_length);

/*!
A appeler à chaque réception d'octet afin de traiter les données en tant que trame.
\param[in] rxByte   octet recu par la série
*/
void interruptionRxTrame(unsigned char rxByte);

/*!
Pour envoyer une donnée sous forme de trame sur le port 2.
\param[in] type   type de trame (voir liste des defines commancants par TYPE_TRAME_...
\param[in] data   le pointeur de la donnée à envoyer
\param[in] data_length  longueur de la trame (voir liste des defines commancants par LG_TRAME_...
*/
void envoiTrameUart2 (char type, void * data, char data_length);

/*!
Réception d'un octet mais sans traitement en tant que trame. 
\param[in] rxByte   octet recu par la série
*/
void interruptionRxOctet(unsigned char rxByte);

/*!
Pour envoyer tous les coef présents en eeprom + le verbose
*/
void envoyerCoefficientsStatiques(void);


#endif


