#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#define LG_TRAME_CON_COUPLEG 2
#define LG_TRAME_CON_COUPLED 2
#define LG_TRAME_INF_COUPLEG 2
#define LG_TRAME_INF_COUPLED 2
#define LG_TRAME_INF_ERREUR_CARTE_COURANT 1

#define LG_TRAME_INF_VITESSEG 4
#define LG_TRAME_INF_VITESSED 4
#define LG_TRAME_INF_PRINC_PID_K 4
#define LG_TRAME_CON_PRINC_PID_K 4
#define LG_TRAME_INF_PRINC_PID_I 4
#define LG_TRAME_CON_PRINC_PID_I 4
#define LG_TRAME_INF_PRINC_PID_D 4
#define LG_TRAME_CON_PRINC_PID_D 4
#define LG_TRAME_INF_PRINC_DIR 4
#define LG_TRAME_CON_PRINC_DIR 4
#define LG_TRAME_INF_ANGLE 4
#define LG_TRAME_INF_VITESSE_ANGULAIRE 4
#define LG_TRAME_INF_ACCELERATION 4
#define LG_TRAME_CON_ACCELERATION_COEF_FILTRE 4
#define LG_TRAME_INF_COEF_KALMAN 4
#define LG_TRAME_CON_COEF_KALMAN 4
#define LG_TRAME_CON_SAUVEGARDER_COEF 4
#define LG_TRAME_INF_DISTANCE_PARCOURUE 4
#define LG_TRAME_INF_ETAT_BATTERIE 4

#define LG_TRAME_CON_STOP 0
#define LG_TRAME_CON_DEPART 0
#define LG_TRAME_INF_PRET 0
#define LG_TRAME_INF_ETAT 1
#define LG_TRAME_CON_TEST_COM 2
#define LG_TRAME_INF_SATURATION_VITESSE 2
#define LG_TRAME_CON_SATURATION_VITESSE 2
#define LG_TRAME_INF_ANGLE_HORS_INTERVALLE 1
#define LG_TRAME_CON_RECHARGER_COEF 1


#define TYPE_TRAME_CON_COUPLEG 138
#define TYPE_TRAME_CON_COUPLED 139
#define TYPE_TRAME_INF_COUPLEG 10
#define TYPE_TRAME_INF_COUPLED 11
#define TYPE_TRAME_INF_ERREUR_CARTE_COURANT 12

#define TYPE_TRAME_INF_VITESSEG 13
#define TYPE_TRAME_INF_VITESSED 14
#define TYPE_TRAME_INF_PRINC_PID_K 15
#define TYPE_TRAME_CON_PRINC_PID_K 143
#define TYPE_TRAME_INF_PRINC_PID_I 16
#define TYPE_TRAME_CON_PRINC_PID_I 144
#define TYPE_TRAME_INF_PRINC_PID_D 17
#define TYPE_TRAME_CON_PRINC_PID_D 145
#define TYPE_TRAME_INF_PRINC_DIR 18
#define TYPE_TRAME_CON_PRINC_DIR 146
#define TYPE_TRAME_INF_ANGLE 19
#define TYPE_TRAME_INF_VITESSE_ANGULAIRE 30
#define TYPE_TRAME_INF_ACCELERATION 20
#define TYPE_TRAME_CON_ACCELERATION_COEF_FILTRE 148
#define TYPE_TRAME_INF_COEF_KALMAN 21
#define TYPE_TRAME_CON_COEF_KALMAN 149
#define TYPE_TRAME_CON_SAUVEGARDER_COEF 150
#define TYPE_TRAME_INF_DISTANCE_PARCOURUE 23
#define TYPE_TRAME_INF_ETAT_BATTERIE 24

#define TYPE_TRAME_CON_STOP 153
#define TYPE_TRAME_CON_DEPART 154
#define TYPE_TRAME_INF_PRET 25
#define TYPE_TRAME_INF_ETAT 26
#define TYPE_TRAME_CON_TEST_COM 155
#define TYPE_TRAME_INF_SATURATION_VITESSE 28
#define TYPE_TRAME_CON_SATURATION_VITESSE 156
#define TYPE_TRAME_INF_ANGLE_HORS_INTERVALLE 29
#define TYPE_TRAME_CON_RECHARGER_COEF 159



#define DEBUT_TRAME 0b01110010
#define TRAME_ERR_NOERR 0
#define TRAME_ERR_TYPE 1
#define TRAME_ERR_CHECK 2
#define TRAME_ERR_DEBUT 3

void envoiTrameUart1 (char type, void * data, char data_length);
void interruptionRx1(unsigned char rxByte);

#endif


