#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#define TYPE_TRAME_CON_COUPLEG 138	
#define LG_TRAME_CON_COUPLEG 1
#define TYPE_TRAME_CON_COUPLED 139	
#define LG_TRAME_CON_COUPLED 1
#define TYPE_TRAME_INF_COUPLEG 10	
#define LG_TRAME_INF_COUPLEG 1
#define TYPE_TRAME_INF_COUPLED 11
#define LG_TRAME_INF_COUPLED 1
#define TYPE_TRAME_INF_ERREUR_CARTE_COURANT 12	
#define LG_TRAME_INF_ERREUR_CARTE_COURANT 1
	
#define TYPE_TRAME_INF_VITESSEG 13	
#define LG_TRAME_INF_VITESSEG 2
#define TYPE_TRAME_INF_VITESSED 14	
#define LG_TRAME_INF_VITESSED 2
#define TYPE_TRAME_INF_PRINC_PID_K 15	
#define LG_TRAME_INF_PRINC_PID_K 2
#define TYPE_TRAME_CON_PRINC_PID_K 143	
#define LG_TRAME_CON_PRINC_PID_K 2
#define TYPE_TRAME_INF_PRINC_PID_I 16	
#define LG_TRAME_INF_PRINC_PID_I 2
#define TYPE_TRAME_CON_PRINC_PID_I 144	
#define LG_TRAME_CON_PRINC_PID_I 2
#define TYPE_TRAME_INF_PRINC_PID_D 17	
#define LG_TRAME_INF_PRINC_PID_D 2
#define TYPE_TRAME_CON_PRINC_PID_D 145	
#define LG_TRAME_CON_PRINC_PID_D 2
#define TYPE_TRAME_INF_PRINC_DIR 18	
#define LG_TRAME_INF_PRINC_DIR 2
#define TYPE_TRAME_CON_PRINC_DIR 146	
#define LG_TRAME_CON_PRINC_DIR 2
#define TYPE_TRAME_INF_ANGLE 19	
#define LG_TRAME_INF_ANGLE 2
#define TYPE_TRAME_INF_VITESSE_ANGULAIRE 19	
#define LG_TRAME_INF_VITESSE_ANGULAIRE 2
#define TYPE_TRAME_INF_ACCELERATION 20
#define LG_TRAME_INF_ACCELERATION 2
#define TYPE_TRAME_CON_ACCELERATION_COEF_FILTRE 148
#define LG_TRAME_CON_ACCELERATION_COEF_FILTRE 2
#define TYPE_TRAME_INF_COEF_KALMAN 21	
#define LG_TRAME_INF_COEF_KALMAN 1
#define TYPE_TRAME_CON_COEF_KALMAN 149
#define LG_TRAME_CON_COEF_KALMAN 1
#define TYPE_TRAME_CON_SAUVEGARDER_COEF 150	
#define LG_TRAME_CON_SAUVEGARDER_COEF 0
#define TYPE_TRAME_INF_DISTANCE_PARCOURUE 23	
#define LG_TRAME_INF_DISTANCE_PARCOURUE 2
#define TYPE_TRAME_INF_ETAT_BATTERIE 24
#define LG_TRAME_INF_ETAT_BATTERIE 2
	
#define TYPE_TRAME_CON_STOP 153	
#define LG_TRAME_CON_STOP 0
#define TYPE_TRAME_CON_DEPART 154	
#define LG_TRAME_CON_DEPART 0
#define TYPE_TRAME_INF_PRET 25
#define LG_TRAME_INF_PRET 0
#define TYPE_TRAME_INF_ETAT 26
#define LG_TRAME_INF_ETAT 1
#define TYPE_TRAME_CON_TEST_COM 155	
#define LG_TRAME_CON_TEST_COM 1
#define TYPE_TRAME_INF_SATURATION_VITESSE 28	
#define LG_TRAME_INF_SATURATION_VITESSE 2
#define TYPE_TRAME_CON_SATURATION_VITESSE 156	
#define LG_TRAME_CON_SATURATION_VITESSE 2
#define TYPE_TRAME_INF_ANGLE_HORS_INTERVALLE 29	
#define LG_TRAME_INF_ANGLE_HORS_INTERVALLE 1


#endif


